version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
      - "8001:8000"
    environment:
      WALLET_NAME: ${WALLET_HOTKEY}
      WALLET_HOTKEY: ${WALLET_HOTKEY}
    volumes:
      - .:/app
